### ISSUE TITLE
Needs new Icon

### ISSUE THREAD

**Issue by Sleeplessani** [nsiebenaller/ui-components#1]
Autorenew Icon needs to be added to the project
![image](https://user-images.githubusercontent.com/69009086/88951285-c2cc8500-d263-11ea-8ff8-07822492d8bf.png)

**Comment by nsiebenaller** [comment]
This icon is added in build 1.0.32

**Comment by Sleeplessani** [comment]
This icon has not been added to the demo page for Icons yet
